name: Pipe

on:
  push:
  pull_request:
    branches:
      - 'main'

  schedule:
  - cron: "0 12 * * 1-5"

jobs:
  regression-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v3
      
      - name: cache clear
        run: npx cypress cache clear

      - name: cypress install
        run: npx cypress install

      - name: Run Cypress Tests ðŸ§ª
        uses: cypress-io/github-action@v5
        with:
          wait-on-timeout: 60
        env:
          BASE_URL: ${{secrets.BASE_URL}}
          NAME: ${{secrets.NAME}}
          PASSWORD: ${{secrets.PASSWORD}}
          USER_ID: ${{secrets.USER_ID}}
          build: npm run build
          start: npm run test

      - name: Deploy to GitHub Pages
        if: always()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./cypress/reports/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
